# Generated by Django 3.2.5 on 2022-06-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0002_auto_20220615_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=12)),
                ('especialidade', models.CharField(max_length=100)),
            ],
        ),
    ]
